const word = document.getElementById('word');
const text = document.getElementById('input_area');
const scoreE1 = document.getElementById('score');
const timeE1 = document.getElementById('end_gane');

const words = [
    "npm cache",
    "vue",
    "hacking world",
    "end",
    "I",
    "all",
    "number",
    "oil",
    "within",
    "now",
    "right",
    "feet",
    "leave",
    "what",
    "now",
    "facebook",
    "came",
    "live",
    "test",
    "about",
    "netflix",
    "came",
    "set",
    "were",
    "follow",
    "study",
    "day",
    "structure",
    "over",
    "why",
    "why",
    "talk",
    "soon",
    "because",
    "random",
    "watch",
    "year",
    "her",
    "any",
    "snapchat",
    "I",
    "both",
    "around",
    "book",
    "line",
    "mother",
    "open",
    "now",
    "defend",
    "mile",
    "go",
    "by",
    "found",
    "said",
    "eye",
    "come",
    "so",
    "place",
    "food",
    "got",
    "city",
    "always",
    "these",
    "any",
    "use",
    "been",
    "was",
    "read",
    "their",
    "without",
    "as",
    "change",
    "leave",
    "can",
    "they",
    "those",
    "eat",
    "never",
    "no",
    "eat",
    "story",
]

let randomWord;
let score = 0;
let time = 60;

function getRandomWord() {
    return words[Math.floor(Math.random()* words.length)]
}